# Eigenvalues and Eigenvectors — Solutions

Solutions for the three questions in the supplied question sheet. fileciteturn2file2L2-L29

## Question 1
Find eigenvalues/eigenvectors of `A=[[4,1],[2,3]]`.

In [1]:
import numpy as np

A = np.array([[4,1],
              [2,3]], dtype=float)

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors (columns):\n", eigenvectors)

Eigenvalues: [5. 2.]
Eigenvectors (columns):
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


### Display each eigenpair

In [2]:
for i, lam in enumerate(eigenvalues):
    v = eigenvectors[:, i]
    print(f"Eigenvalue {lam:.6f}")
    print("Eigenvector:", v)
    print()

Eigenvalue 5.000000
Eigenvector: [0.70710678 0.70710678]

Eigenvalue 2.000000
Eigenvector: [-0.4472136   0.89442719]



## Question 2
Find eigenvalues/eigenvectors of `A=[[4,1,0],[1,4,1],[0,1,4]]`, then sort by decreasing eigenvalue.

In [3]:
A = np.array([[4,1,0],
              [1,4,1],
              [0,1,4]], dtype=float)

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Original eigenvalues:", eigenvalues)
print("Original eigenvectors:\n", eigenvectors)

Original eigenvalues: [2.58578644 4.         5.41421356]
Original eigenvectors:
 [[ 5.00000000e-01  7.07106781e-01  5.00000000e-01]
 [-7.07106781e-01  1.37464400e-16  7.07106781e-01]
 [ 5.00000000e-01 -7.07106781e-01  5.00000000e-01]]


In [4]:
order = np.argsort(eigenvalues)[::-1]
sorted_values = eigenvalues[order]
sorted_vectors = eigenvectors[:, order]

print("Sorted eigenvalues:", sorted_values)
print("Sorted eigenvectors (columns):\n", sorted_vectors)

for i, lam in enumerate(sorted_values):
    print(f"lambda = {lam:.6f}, v = {sorted_vectors[:, i]}")

Sorted eigenvalues: [5.41421356 4.         2.58578644]
Sorted eigenvectors (columns):
 [[ 5.00000000e-01  7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  1.37464400e-16 -7.07106781e-01]
 [ 5.00000000e-01 -7.07106781e-01  5.00000000e-01]]
lambda = 5.414214, v = [0.5        0.70710678 0.5       ]
lambda = 4.000000, v = [ 7.07106781e-01  1.37464400e-16 -7.07106781e-01]
lambda = 2.585786, v = [ 0.5        -0.70710678  0.5       ]


## Question 3
Diagonalize `A=[[2,1,0],[0,3,1],[0,0,4]]` and verify \(AP=PD\).

In [5]:
A = np.array([[2,1,0],
              [0,3,1],
              [0,0,4]], dtype=float)

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2. 3. 4.]
Eigenvectors:
 [[1.         0.70710678 0.33333333]
 [0.         0.70710678 0.66666667]
 [0.         0.         0.66666667]]


In [6]:
# Use columns of eigenvectors to form P, and eigenvalues in the same order for D.
P = eigenvectors
D = np.diag(eigenvalues)

print("P =\n", P)
print("\nD =\n", D)

P =
 [[1.         0.70710678 0.33333333]
 [0.         0.70710678 0.66666667]
 [0.         0.         0.66666667]]

D =
 [[2. 0. 0.]
 [0. 3. 0.]
 [0. 0. 4.]]


In [7]:
AP = A @ P
PD = P @ D

print("A @ P =\n", AP)
print("\nP @ D =\n", PD)
print("\nDiagonalization verified?", np.allclose(AP, PD))

A @ P =
 [[2.         2.12132034 1.33333333]
 [0.         2.12132034 2.66666667]
 [0.         0.         2.66666667]]

P @ D =
 [[2.         2.12132034 1.33333333]
 [0.         2.12132034 2.66666667]
 [0.         0.         2.66666667]]

Diagonalization verified? True
