# Principal Component Analysis (PCA) — Solutions

Solutions for the three questions in the supplied question sheet. fileciteturn2file0L2-L39

## Question 1
Convert the 2-feature dataset to NumPy, compute feature means, and center it.

In [1]:
import numpy as np

X = np.array([[2,4],
              [3,5],
              [4,6],
              [5,8],
              [6,9]], dtype=float)

print("X =\n", X)

X =
 [[2. 4.]
 [3. 5.]
 [4. 6.]
 [5. 8.]
 [6. 9.]]


In [2]:
mean = np.mean(X, axis=0)
X_centered = X - mean

print("Feature means:", mean)
print("\nCentered data =\n", X_centered)

Feature means: [4.  6.4]

Centered data =
 [[-2.  -2.4]
 [-1.  -1.4]
 [ 0.  -0.4]
 [ 1.   1.6]
 [ 2.   2.6]]


## Question 2
Center the same dataset, compute its covariance matrix, find its eigenpairs, sort the eigenvalues, and identify the first principal component.

In [3]:
X = np.array([[2,4],
              [3,5],
              [4,6],
              [5,8],
              [6,9]], dtype=float)

mean = np.mean(X, axis=0)
X_centered = X - mean
cov_matrix = np.cov(X_centered, rowvar=False)

print("Centered data =\n", X_centered)
print("\nCovariance matrix =\n", cov_matrix)

Centered data =
 [[-2.  -2.4]
 [-1.  -1.4]
 [ 0.  -0.4]
 [ 1.   1.6]
 [ 2.   2.6]]

Covariance matrix =
 [[2.5  3.25]
 [3.25 4.3 ]]


In [4]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
order = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[order]
eigenvectors = eigenvectors[:, order]

print("Eigenvalues:", eigenvalues)
print("Eigenvectors (columns):\n", eigenvectors)
print("\nFirst principal component:", eigenvectors[:,0])

Eigenvalues: [6.77231375 0.02768625]
Eigenvectors (columns):
 [[-0.60544237 -0.79588915]
 [-0.79588915  0.60544237]]

First principal component: [-0.60544237 -0.79588915]


## Question 3
Perform PCA on the 3-feature dataset, sort components, calculate explained variance, and project onto the first two components.

In [5]:
X = np.array([[2,4,1],
              [3,5,2],
              [4,6,3],
              [5,8,4],
              [6,9,5]], dtype=float)

mean = np.mean(X, axis=0)
X_centered = X - mean
cov_matrix = np.cov(X_centered, rowvar=False)

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
order = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[order]
eigenvectors = eigenvectors[:, order]

print("Mean:", mean)
print("\nCentered data =\n", X_centered)
print("\nCovariance matrix =\n", cov_matrix)
print("\nEigenvalues:", eigenvalues)
print("\nEigenvectors (columns):\n", eigenvectors)

Mean: [4.  6.4 3. ]

Centered data =
 [[-2.  -2.4 -2. ]
 [-1.  -1.4 -1. ]
 [ 0.  -0.4  0. ]
 [ 1.   1.6  1. ]
 [ 2.   2.6  2. ]]

Covariance matrix =
 [[2.5  3.25 2.5 ]
 [3.25 4.3  3.25]
 [2.5  3.25 2.5 ]]

Eigenvalues: [9.25950106e+00 4.04989424e-02 5.99331377e-16]

Eigenvectors (columns):
 [[-5.18635259e-01  4.80642766e-01 -7.07106781e-01]
 [-6.79731518e-01 -7.33461017e-01 -1.54519208e-14]
 [-5.18635259e-01  4.80642766e-01  7.07106781e-01]]


In [6]:
explained_variance_ratio = eigenvalues / np.sum(eigenvalues)
explained_percentage = explained_variance_ratio * 100

print("Explained variance (%):", explained_percentage)

W = eigenvectors[:, :2]
projected = X_centered @ W

print("\nFirst two principal components:\n", W)
print("\nProjected data onto first two PCs =\n", projected)

Explained variance (%): [9.95645275e+01 4.35472499e-01 6.44442341e-15]

First two principal components:
 [[-0.51863526  0.48064277]
 [-0.67973152 -0.73346102]
 [-0.51863526  0.48064277]]

Projected data onto first two PCs =
 [[ 3.70589668 -0.16226462]
 [ 1.98889464  0.06555989]
 [ 0.27189261  0.29338441]
 [-2.12484095 -0.2122521 ]
 [-3.84184298  0.01557242]]
